name: shopping_app
description: This is a simple shopping list app for multiple user can shop from single shopping list
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  # to manage state and code organization
  bloc: ^8.1.0

  # to compare and hash code of the class
  equatable: ^2.0.5

  # to access firebase realtime database
  firebase_core: ^1.21.1
  firebase_database: ^9.1.3

  flutter:
    sdk: flutter

  # to use cubit from block
  flutter_bloc: ^8.1.1

  # to support internationalization
  flutter_localizations:
    sdk: flutter

  # to show toast message
  fluttertoast: ^8.0.9

  # to network call
  http: ^0.13.5

  # to support internationalization
  intl: ^0.17.0

dev_dependencies:
  # to mock cubit and test with cubit
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter

  # to mock classes
  mocktail: ^0.3.0

  # to analysis with best practice
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
